backend:
  name: github
  repo: Ildebranda/site-ildebranda
  branch: master

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: obras
    label: Obras
    folder: content/obras
    create: true
    fields:
      - { label: Título, name: title, widget: string }
      - { label: Imagem, name: image, widget: image }

  - name: exposicoes
    label: Exposições
    folder: content/exposicoes
    create: true
    fields:
      - { label: Título, name: title, widget: string }

  - name: noticias
    label: Notícias
    folder: content/blog
    create: true
    fields:
      - { label: Título, name: title, widget: string }
      - { label: Texto, name: body, widget: markdown }
